# Generated by Django 5.2.17 on 2026-09-17 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('price_chf_cents', models.PositiveIntegerField(default=0)),
                ('interval', models.CharField(default='month', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_decks', models.PositiveIntegerField(blank=True, null=True)),
                ('max_games_per_run', models.PositiveIntegerField(default=10000)),
                ('max_turns', models.PositiveIntegerField(default=6)),
                ('max_runs_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_concurrent_runs', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='active', max_length=16)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('metric', models.CharField(choices=[('runs_started', 'Runs started'), ('games_simulated', 'Games simulated'), ('imports', 'Imports'), ('decks_created', 'Decks created')], max_length=32)),
                ('amount', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'period_start'], name='billing_usa_user_id_a9a3f4_idx')],
                'unique_together': {('user', 'period_start', 'metric')},
            },
        ),
    ]
