# Generated by Django 5.2.17 on 2026-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_max_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
