# Generated by Django 5.2.17 on 2026-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_plan_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagerecord",
            name="metric",
            field=models.CharField(
                choices=[
                    ("runs_started", "Runs started"),
                    ("games_simulated", "Games simulated"),
                    ("imports", "Imports"),
                    ("decks_created", "Decks created"),
                    ("summaries_written", "Summaries written"),
                ],
                max_length=32,
            ),
        ),
    ]
