# Generated by Django 5.2.17 on 2026-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_load_protection"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="annual_prices",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plan",
            name="stripe_annual_price_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
