# Generated by Django 5.2.17 on 2026-09-18 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaytestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deck_snapshot', models.JSONField(default=dict)),
                ('seed', models.BigIntegerField()),
                ('on_the_play', models.BooleanField(default=True)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('cards_total', models.PositiveIntegerField(default=0)),
                ('cards_with_gaps', models.PositiveIntegerField(default=0)),
                ('cached_state', models.JSONField(blank=True, default=dict)),
                ('cached_seq', models.IntegerField(blank=True, null=True)),
                ('forked_at_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtests', to='decks.deck')),
                ('forked_from', models.ForeignKey(blank=True, help_text='The session this one branched off, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='playtest.playtestsession')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PlaytestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='playtest.playtestsession')),
            ],
            options={
                'ordering': ('seq',),
            },
        ),
        migrations.AddIndex(
            model_name='playtestsession',
            index=models.Index(fields=['owner', '-updated_at'], name='playtest_pl_owner_i_94ecab_idx'),
        ),
        migrations.AddConstraint(
            model_name='playtestaction',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='playtest_action_seq_unique'),
        ),
    ]
