# Generated by Django 5.2.17 on 2026-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtestsession',
            name='copies_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playtestsession',
            name='copies_unreadable',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
