# Generated by Django 5.2.17 on 2026-09-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0006_derivedprofile_skips_draw_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('scryfall_id', models.CharField(blank=True, max_length=64)),
                ('set_code', models.CharField(blank=True, max_length=16)),
                ('collector_number', models.CharField(blank=True, max_length=16)),
                ('finish', models.CharField(blank=True, max_length=32)),
                ('condition', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collection.collection')),
                ('oracle_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='cards.oraclecard')),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'oracle_card'], name='collection__collect_254032_idx')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'oracle_card', 'set_code', 'collector_number', 'finish'), name='uniq_collection_printing')],
            },
        ),
    ]
