# Generated by Django 5.2.17 on 2026-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collectionitem_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='column_mapping',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
