# Generated by Django 5.2.17 on 2026-09-21 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0007_alter_bulkimport_kind_printing'),
        ('decks', '0003_column_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('spellbook_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('identity', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(blank=True, max_length=16)),
                ('bracket_tag', models.CharField(blank=True, max_length=8)),
                ('mana_needed', models.CharField(blank=True, max_length=64)),
                ('mana_value_needed', models.PositiveSmallIntegerField(default=0)),
                ('notable_prerequisites', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('legal_commander', models.BooleanField(default=True)),
                ('produces', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity', 'spellbook_id'],
            },
        ),
        migrations.CreateModel(
            name='ComboLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('identity', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('ok', 'Fetched'), ('failed', 'Could not be fetched')], default='ok', max_length=16)),
                ('message', models.CharField(blank=True, max_length=256)),
                ('out_of_identity', models.PositiveIntegerField(default=0)),
                ('needs_other_commanders', models.PositiveIntegerField(default=0)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combo_lookup', to='decks.deck')),
            ],
        ),
        migrations.CreateModel(
            name='ComboTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('scryfall_query', models.CharField(blank=True, max_length=512)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='combos.combo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComboCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oracle_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('must_be_commander', models.BooleanField(default=False)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='combos.combo')),
                ('oracle_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_combos', to='cards.oraclecard')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['oracle_card'], name='combos_comb_oracle__e606e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeckCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('included', 'In the deck'), ('one_away', 'One card away')], max_length=16)),
                ('missing', models.JSONField(blank=True, default=list)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_decks', to='combos.combo')),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='combos.combolookup')),
            ],
            options={
                'ordering': ['kind', '-combo__popularity'],
                'constraints': [models.UniqueConstraint(fields=('lookup', 'combo'), name='one_row_per_combo_per_deck')],
            },
        ),
    ]
