# Generated by Django 5.2.17 on 2026-09-21 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_bulkimport_kind_printing'),
        ('combos', '0001_initial'),
        ('decks', '0003_column_mapping'),
        ('simulations', '0002_simulationrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('included', 'In the deck'), ('one_away', 'One card away')], max_length=16)),
                ('added_name', models.CharField(blank=True, max_length=256)),
                ('games', models.PositiveIntegerField()),
                ('turns', models.PositiveSmallIntegerField()),
                ('by_turn', models.JSONField(blank=True, default=list)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('added_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.oraclecard')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='combos.combo')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_measurements', to='decks.deck')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_measurements', to='simulations.simulationrun')),
            ],
            options={
                'ordering': ['kind', '-combo__popularity'],
                'indexes': [models.Index(fields=['deck', '-measured_at'], name='combos_comb_deck_id_de2379_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'combo'), name='one_measurement_per_combo_per_run')],
            },
        ),
    ]
