# Generated by Django 5.2.17 on 2026-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deck_summaries',
            field=models.BooleanField(default=True),
        ),
    ]
