# Generated by Django 5.2.17 on 2026-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="simulated_week",
            field=models.DateField(blank=True, null=True),
        ),
    ]
