# Generated by Django 5.2.17 on 2026-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_simulated_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
