# Generated by Django 5.2.17 on 2026-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_privacy_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="changelog_mail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="changelog_mail_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="changelog_mailed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
