# Generated by Django 5.2.17 on 2026-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("guest_started", "Guests started"),
                            ("guest_saved", "Guests saved as an account"),
                            ("signup", "Accounts opened"),
                            ("run_guest", "Simulations started by guests"),
                            ("run_member", "Simulations started by accounts"),
                            ("simulator_guest", "Guests who simulated"),
                            ("simulator_member", "Accounts that simulated"),
                            ("report_opened", "Shared reports opened"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-day", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "name"), name="one_count_per_day_and_name"
                    )
                ],
            },
        ),
    ]
