# Generated by Django 5.2.17 on 2026-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_fake_door"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycount",
            name="name",
            field=models.CharField(
                choices=[
                    ("guest_started", "Guests started"),
                    ("guest_saved", "Guests saved as an account"),
                    ("signup", "Accounts opened"),
                    ("run_guest", "Simulations started by guests"),
                    ("run_member", "Simulations started by accounts"),
                    ("simulator_guest", "Guests who simulated"),
                    ("simulator_member", "Accounts that simulated"),
                    ("report_opened", "Shared reports opened"),
                    ("report_viewed", "Reports viewed"),
                    ("compare_clicked", "Compare two versions clicked"),
                    ("data_page_opened", "Data pages opened"),
                ],
                max_length=32,
            ),
        ),
    ]
