# Generated by Django 5.2.17 on 2026-09-17 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_oraclecard_scryfall_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('format', models.CharField(choices=[('commander', 'Commander')], default='commander', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands_decks', to='cards.oraclecard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='decks.deck')),
                ('oracle_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_decks', to='cards.oraclecard')),
            ],
            options={
                'ordering': ['oracle_card__cmc', 'oracle_card__name'],
            },
        ),
        migrations.CreateModel(
            name='DeckImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('parser', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('review', 'Awaiting review'), ('applied', 'Applied'), ('abandoned', 'Abandoned')], default='review', max_length=16)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_resolved', models.PositiveIntegerField(default=0)),
                ('rows_unresolved', models.PositiveIntegerField(default=0)),
                ('rung_counts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='decks.deck')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnresolvedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('raw_name', models.CharField(max_length=256)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.CharField(max_length=200)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('deck_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved', to='decks.deckimport')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['owner', '-updated_at'], name='decks_deck_owner_i_dbfe9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.UniqueConstraint(fields=('deck', 'oracle_card'), name='uniq_deck_card'),
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='deck_card_qty'),
        ),
    ]
