# Generated by Django 5.2.17 on 2026-09-20 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deck', 'Deck'), ('collection', 'Collection')], max_length=16)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('parser', models.CharField(blank=True, max_length=32)),
                ('deck_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_imports', to='decks.deck')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'kind'), name='one_pending_import_per_kind')],
            },
        ),
    ]
