# Generated by Django 5.2.17 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_pending_import_deck_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='open_questions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
