# Generated by Django 5.2.17 on 2026-10-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("decks", "0006_open_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Precon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("set_code", models.CharField(max_length=8)),
                ("set_name", models.CharField(blank=True, max_length=120)),
                ("released", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("mtgjson", "MTGJSON"), ("text", "Text list")],
                        max_length=8,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=160)),
                ("list_print", models.CharField(blank=True, max_length=64)),
                ("unmatched", models.JSONField(blank=True, default=list)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precon",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["-released", "name"],
            },
        ),
    ]
