# Generated by Django 5.2.17 on 2026-10-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datapages", "0001_initial"),
        ("decks", "0006_open_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandSweep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lands", models.PositiveSmallIntegerField()),
                ("list_print", models.CharField(max_length=64)),
                (
                    "deck",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_sweep",
                        to="decks.deck",
                    ),
                ),
                (
                    "precon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sweeps",
                        to="datapages.precon",
                    ),
                ),
            ],
            options={
                "ordering": ["precon", "lands"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("precon", "lands"), name="one_sweep_per_land_count"
                    )
                ],
            },
        ),
    ]
