# Generated by Django 5.2.17 on 2026-09-17 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_oraclecard_scryfall_id'),
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, help_text='Why, for the provenance panel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(blank=True, help_text="Null means it applies to all of the owner's decks.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_annotations', to='decks.deck')),
                ('oracle_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cards.oraclecard')),
                ('owner', models.ForeignKey(blank=True, help_text='Null means a built-in default that applies to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['deck', 'oracle_card'], name='simulations_deck_id_9ad389_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'deck', 'oracle_card'), name='uniq_card_annotation', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('deck__isnull', True), ('owner__isnull', False), _connector='OR'), name='deck_annotation_needs_owner')],
            },
        ),
    ]
