# Generated by Django 5.2.17 on 2026-09-18 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('games_total', models.PositiveIntegerField()),
                ('turns', models.PositiveSmallIntegerField(default=3)),
                ('on_the_play', models.BooleanField(default=True)),
                ('seed', models.BigIntegerField()),
                ('games_done', models.PositiveIntegerField(default=0)),
                ('chunks_total', models.PositiveIntegerField(default=0)),
                ('chunks_done', models.PositiveIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('cards_total', models.PositiveIntegerField(default=0)),
                ('cards_with_gaps', models.PositiveIntegerField(default=0)),
                ('library_size', models.PositiveIntegerField(default=0)),
                ('lands_total', models.PositiveIntegerField(default=0)),
                ('engine_version', models.PositiveSmallIntegerField(default=0)),
                ('usec_per_game', models.FloatField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='decks.deck')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deck', '-created_at'], name='simulations_deck_id_7f2cde_idx'), models.Index(fields=['owner', 'status'], name='simulations_owner_i_aaa2ac_idx')],
            },
        ),
    ]
