# Generated by Django 5.2.17 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_simulationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardannotation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
