# Generated by Django 5.2.17 on 2026-10-02 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_open_questions'),
        ('simulations', '0004_simulationrun_copies_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Being written'), ('done', 'Written'), ('failed', 'Could not be written')], default='pending', max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.PositiveSmallIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('charged', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='decks.deck')),
            ],
        ),
    ]
