# Generated by Django 5.2.17 on 2026-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_decksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='deck_print',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
