# Generated by Django 5.2.17 on 2026-10-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_simulationrun_deck_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='decksummary',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
