# Generated by Django 5.2.17 on 2026-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0007_decksummary_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("guests", models.PositiveIntegerField(default=0)),
                ("members", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="decksummary",
            name="budget_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decksummary",
            name="budget_guest",
            field=models.BooleanField(default=False),
        ),
    ]
