# Generated by Django 5.2.17 on 2026-10-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0011_bulkimport_sets_fingerprint"),
        ("simulations", "0008_load_protection"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnreadCard",
            fields=[
                (
                    "oracle_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="unread",
                        serialize=False,
                        to="cards.oraclecard",
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("seen", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                ("engine_version", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("read", "Read now"),
                            ("wont_fix", "Won't fix"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("read_since", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("mailed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-seen",),
                "indexes": [
                    models.Index(
                        fields=["status", "mailed_at"],
                        name="simulations_status_9369d3_idx",
                    )
                ],
            },
        ),
    ]
