# Generated by Django 5.2.17 on 2026-09-17 21:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OracleCard',
            fields=[
                ('oracle_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('front_name', models.CharField(db_index=True, max_length=256)),
                ('search_name', models.CharField(db_index=True, max_length=256)),
                ('mana_cost', models.CharField(blank=True, max_length=128)),
                ('cmc', models.FloatField(default=0)),
                ('type_line', models.CharField(blank=True, max_length=256)),
                ('oracle_text', models.TextField(blank=True)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, size=None)),
                ('color_identity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, size=None)),
                ('produced_mana', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('layout', models.CharField(blank=True, max_length=32)),
                ('power', models.CharField(blank=True, max_length=8)),
                ('toughness', models.CharField(blank=True, max_length=8)),
                ('loyalty', models.CharField(blank=True, max_length=8)),
                ('legalities', models.JSONField(blank=True, default=dict)),
                ('game_changer', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('edhrec_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('scryfall_uri', models.URLField(blank=True, max_length=512)),
                ('image_uri', models.URLField(blank=True, max_length=512)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='BulkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('oracle_cards', 'Oracle cards'), ('oracle_tags', 'Oracle tags')], max_length=32)),
                ('scryfall_updated_at', models.DateTimeField(help_text="The bulk file's own timestamp, not ours. The idempotency key.")),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped (unchanged)')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_seen', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('peak_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', 'status', 'scryfall_updated_at'], name='cards_bulki_kind_87a0aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OracleCardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct', models.BooleanField(default=True)),
                ('weight', models.CharField(blank=True, max_length=16)),
                ('oracle_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tags', to='cards.oraclecard')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tags', to='cards.tag')),
            ],
        ),
        migrations.AddField(
            model_name='oraclecard',
            name='tags',
            field=models.ManyToManyField(related_name='cards', through='cards.OracleCardTag', to='cards.tag'),
        ),
        migrations.CreateModel(
            name='TagEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='cards.tag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='cards.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='oraclecardtag',
            index=models.Index(fields=['tag', 'is_direct'], name='cards_oracl_tag_id_bc1eb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='oraclecardtag',
            constraint=models.UniqueConstraint(fields=('oracle_card', 'tag'), name='uniq_card_tag'),
        ),
        migrations.AddIndex(
            model_name='oraclecard',
            index=models.Index(fields=['cmc'], name='cards_oracl_cmc_3ed515_idx'),
        ),
        migrations.AddIndex(
            model_name='oraclecard',
            index=models.Index(fields=['game_changer'], name='cards_oracl_game_ch_f0ca28_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagedge',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uniq_tag_edge'),
        ),
        migrations.AddConstraint(
            model_name='tagedge',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='tag_edge_not_self'),
        ),
    ]
