# Generated by Django 5.2.17 on 2026-09-17 21:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProfile',
            fields=[
                ('oracle_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='cards.oraclecard')),
                ('mv', models.PositiveSmallIntegerField(default=0)),
                ('pips', models.JSONField(blank=True, default=dict)),
                ('generic', models.PositiveSmallIntegerField(default=0)),
                ('colorless', models.PositiveSmallIntegerField(default=0, help_text='{C} pips, which generic mana cannot pay.')),
                ('has_x', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('land', 'Land'), ('rock', 'Mana rock'), ('ritual', 'Ritual'), ('creature', 'Creature'), ('enchantment', 'Enchantment'), ('artifact', 'Artifact'), ('sorcery', 'Sorcery'), ('instant', 'Instant'), ('planeswalker', 'Planeswalker')], max_length=16)),
                ('is_basic_swamp', models.BooleanField(default=False)),
                ('role_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('enters_tapped', models.BooleanField(default=False)),
                ('produces_mana', models.BooleanField(default=False)),
                ('mana_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None)),
                ('mana_amount', models.PositiveSmallIntegerField(blank=True, help_text="Null means unresolved, never 'none'.", null=True)),
                ('cost_reduction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draws_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('self_life_loss', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opponent_life_loss', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('review_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('source_map', models.JSONField(blank=True, default=dict)),
                ('derived_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind'], name='cards_deriv_kind_463d89_idx')],
            },
        ),
    ]
