# Generated by Django 5.2.17 on 2026-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_derivedprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedprofile',
            name='mv',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
