# Generated by Django 5.2.17 on 2026-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_derivedprofile_mv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedprofile',
            name='generic',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
