# Generated by Django 5.2.17 on 2026-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_derivedprofile_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraclecard',
            name='scryfall_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
