# Generated by Django 5.2.17 on 2026-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_oraclecard_scryfall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='skips_draw_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='tutor_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Null means unresolved, never 'one'.", null=True),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='tutor_kind',
            field=models.CharField(blank=True, help_text='Engine card kind the search is restricted to. Blank means any.', max_length=16),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='tutor_to',
            field=models.CharField(blank=True, help_text='hand, graveyard or battlefield. Blank means not a tutor.', max_length=16),
        ),
    ]
