# Generated by Django 5.2.17 on 2026-09-20 17:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_derivedprofile_skips_draw_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkimport',
            name='kind',
            field=models.CharField(choices=[('oracle_cards', 'Oracle cards'), ('oracle_tags', 'Oracle tags'), ('default_cards', 'Printings')], max_length=32),
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('scryfall_id', models.UUIDField(primary_key=True, serialize=False)),
                ('set_code', models.CharField(db_index=True, max_length=16)),
                ('set_name', models.CharField(blank=True, max_length=128)),
                ('collector_number', models.CharField(max_length=32)),
                ('rarity', models.CharField(blank=True, max_length=16)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('finishes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
                ('digital', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('image_uri', models.URLField(blank=True, max_length=512)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_eur_foil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prices_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('oracle_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='cards.oraclecard')),
            ],
            options={
                'ordering': ['set_code', 'collector_number'],
                'indexes': [models.Index(fields=['set_code', 'collector_number'], name='cards_print_set_cod_20d1f5_idx'), models.Index(fields=['oracle_card'], name='cards_print_oracle__cbe090_idx')],
            },
        ),
    ]
