# Generated by Django 5.2.17 on 2026-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_bulkimport_kind_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_activation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_produces',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_untaps',
            field=models.BooleanField(default=True),
        ),
    ]
