# Generated by Django 5.2.17 on 2026-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_printings_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraclecard',
            name='art_uri',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
