# Generated by Django 5.2.17 on 2026-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_oraclecard_art_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimport',
            name='sets_fingerprint',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
