# Generated by Django 5.2.17 on 2026-10-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0011_bulkimport_sets_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedprofile",
            name="land_search",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
