# Generated by Django 5.2.17 on 2026-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_land_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedprofile",
            name="tapped_unless",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
