# Generated by Django 5.2.17 on 2026-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0013_tapped_unless"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedprofile",
            name="mana_condition",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="derivedprofile",
            name="mana_rule",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
