# Generated by Django 5.2.17 on 2026-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0014_mana_condition_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedprofile",
            name="mana_filter",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
