# Generated by Django 5.2.17 on 2026-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0015_mana_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedprofile",
            name="discard_cost",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="derivedprofile",
            name="treasures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
