# Generated by Django 5.2.17 on 2026-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_treasures_discard'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='discards_after',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='extra_cost',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='puts_back',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
