# Generated by Django 5.2.17 on 2026-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_draw_discard_spree'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='draws_x',
            field=models.BooleanField(default=False),
        ),
    ]
