# Generated by Django 5.2.17 on 2026-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_draws_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='tutor_filter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
