# Generated by Django 5.2.17 on 2026-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_tutor_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedprofile',
            name='tutor_to',
            field=models.CharField(blank=True, help_text='hand, graveyard, battlefield or top. Blank means not a tutor.', max_length=16),
        ),
    ]
