# Generated by Django 5.2.17 on 2026-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_tutor_to_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='landers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
