# Generated by Django 5.2.17 on 2026-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_landers'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='additional_cost',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_from_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='sacrifice_mana',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
