# Generated by Django 5.2.17 on 2026-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_sacrifice_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='triggers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
