# Generated by Django 5.2.17 on 2026-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_spend_only',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
