# Generated by Django 5.2.17 on 2026-10-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_spend_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_chosen_color',
            field=models.BooleanField(default=False),
        ),
    ]
