# Generated by Django 5.2.17 on 2026-10-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_chosen_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedprofile',
            name='mana_mills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='mox',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='derivedprofile',
            name='tap_mana',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
