# Generated by Django 5.2.17 on 2026-10-06 14:44

import django.db.models.deletion
import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulations", "0008_load_protection"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=sharing.models.new_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("deck_name", models.CharField(max_length=120)),
                ("commander", models.CharField(blank=True, max_length=256)),
                ("cards", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("summary_language", models.CharField(blank=True, max_length=8)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share",
                        to="simulations.simulationrun",
                    ),
                ),
            ],
        ),
    ]
